### ISSUE TITLE
Doesn't loop seamlessly

### ISSUE THREAD

**Issue by babloyi** [thetwom/toc2#37] opened 2021-07-14 16:56 UTC
Testing on v4.0.0-beta2, I seem to remember this not being an issue before.
I want a vibration on the 2nd beat, then the 4th beat, then the 7th beat (e.g. 2,2,3,2,2,3,2,2,3...), so I mute the other beats, and leave those.
Unfortunately, the first beat starts immediately when I tap play, so it ends up being 2,3,2,2,3,2,2,3,.. (i.e., I have to wait one cycle before the beats loop seamlessly).

Sorry if my wording is confusing!

**Comment by thetwom** [comment] 2021-07-15 13:07
Thanks for testing. Your described behavior a bit unexpected. However, I figured out a problem for vibration of pause notes .... Before I try deeper to understand, what is happening in your case, can you try the fix: [v4.0.0-beta3](https://github.com/thetwom/toc2/releases/tag/v4.0.0-beta3) ?

**Comment by babloyi** [comment] 2021-07-15 16:05
Tried the new build, but I am having the same problem. Also, just a note, this problem was occuring whether I used vibrations only or sound or sound and vibrations (in both builds).

**Comment by thetwom** [comment] 2021-07-15 16:56
I feared, that the version does not fix it ...

Maybe you can give me support by giving more detailed situation:
- Does the situation depend on the notes?
- Is it also skip playing the sound of the first note?
- Does it skip the visualization of the note?
- Are visualization, sound, vibration in sync?

Is it just skipping the first note always? Sound, visualization and vibration?

**Comment by babloyi** [comment] 2021-07-15 18:49
![image](https://user-images.githubusercontent.com/21080590/125840351-1beea36e-ea94-47d8-96ae-b899b84b9683.png)
Here is an example setup (don't mind the colour, I have my blue-light filter on).

-  It does the same thing no matter what the note is
- As I said, my setup has the first note muted, but if I have it unmuted, it plays immediately
- Visualisation is not skipped
- They are all in sync

So in the example I provided, here is the timeline:

1. 2 seconds (2 seconds after the start): vibration
2. 6 seconds (4 seconds after the last vibration): vibration
3. 12 seconds (6 seconds after the last vibration): vibration
4. 16 seconds (4 seconds after the last vibration): vibration
5. 20 seconds (4 seconds after the last vibration): vibration
6. 26 seconds (6 seconds after the last vibration): vibration
(and it continues like 4,5,6 forever in a loop)

My problem is that it doesn't loop seamlessly for the first vibration, because the very first note is played immediately after tapping play, rather than after 2 seconds.

**Comment by thetwom** [comment] 2021-07-16 05:35
Hi, thanks for the detailed description. Please let me repeat in my words in order to see if I understand it correctly:

So the timelime you described is what you would expect:
- Press play
- Directly after play: note 1 is animating, but there is no vibration
- 2s later: first vibration and note 2 animating
- 2s later: note 3 is animating, but no vibration
- 2s later: second vibration and note 4 animating 
- .... 

And what you get is:
- Press play
- You directly get the first vibration (and note 2 is animating, so note 1 is skipped)
- 2s later: note 3 is animating but no vibration
- 2s later: you get the second vibration and note 4 animating
- ...

Is this correct? If yes ... is this also happening for other note settings (e.g. just two notes: first note mute, second note not mute). Would the behavior change if you have other speeds?

**Comment by babloyi** [comment] 2021-07-16 11:31
What I would expect is something like:
1. (0s) I tap play
2. (4s) I get the 1st vibration (on the 2nd note)
2. (8s) I get the 2nd vibration (on the 4th note)
3. (14s) I get the 3rd vibration (on the 7th note)
4. Repeats from step 2, but with +14s (i.e. at 18s I get the 2nd note repeated)

Instead I get:
1. (0s) I tap play and the first note animates (but no vibration or note)
2. (2s) I get the 1st vibration (on the 2nd note)
3. (6s) I get the 2nd vibration (on the 4th note)
4. (12s) I get the 3rd vibration (on the 7th note)
5. (16s) step 2 is repeated, and now after this point it loops seamlessly

The problem I have is that the time between the start and the first vibration (2nd note) is 2s, but the time between the 3rd vibration (7th note) and the next vibration (1st note) is 4s, so I have to discard the first loop completely. If I add an extra silent note at the start (so that there are a total of 8 notes), the first loop works fine, but then the subsequent loops are wrong (time between the 8th note and the vibration of the 3rd note is 6 seconds instead of 4).

It's possible I'm using the system wrong, but I can't see how I can set it up to do what I wish- an infinite, seamless loop of beats on 4,4,6:

- (4s) beat
- (8s) beat
- (14s) beat
- (18s) beat
- (22s) beat
- (28s) beat
and so on

**Comment by thetwom** [comment] 2021-07-16 12:11
Ok, thanks for the further description. Based on that the metronome is working as expected. 

In order to get what you expect, you can use the following
note 1: mute
note 2: vibrate
note 3: mute
note 4: vibrate
note 6: mute
note 5: mute
note 6: vibrate
Let me know if this solves your problem.

**Comment by thetwom** [comment] 2021-07-16 12:16
Thanks for the explanation. Based on this, the metronome works as expected. But it seems that you expect a first cycle which is different. To get close to what you expect, you can try something like
note1: vibrate
note 2: pause
note 3: vibrate
note 4: pause
note 5: vibrate
note 6: pause
note 7: pause
However, this will have one vibrate directly after starting play ...

**Comment by thetwom** [comment] 2021-07-24 06:00
Closing this now since this is not a bug.

**Closed by thetwom** 2021-07-24 06:00 UTC
